"""
Sector-wise sources for all-India government jobs.
NOTE: URLs were written from knowledge, not live-tested. Run:  python job_alerts.py --check
It reports which URLs are dead/blocked so you can fix or delete them.
Format: "Name": "url"   (add/remove freely)
"""

SOURCES = {

    # ---------------- CENTRAL COMMISSIONS & ALL-INDIA PORTALS ----------------
    "Central": {
        "UPSC": "https://upsc.gov.in/whats-new",
        "SSC": "https://ssc.gov.in/",
        "NCS Portal": "https://www.ncs.gov.in/",
        "Employment News": "https://www.employmentnews.gov.in/",
        "NTA": "https://nta.ac.in/",
        "DoPT": "https://dopt.gov.in/",
        "Cabinet Secretariat": "https://cabsec.gov.in/",
        "NIC": "https://www.nic.in/",
        "CSIR": "https://www.csir.res.in/",
        "ICAR": "https://icar.org.in/",
        "ICMR": "https://www.icmr.gov.in/",
    },

    # ---------------- BANKING, INSURANCE, FINANCE ----------------
    "Banking": {
        "SBI": "https://sbi.co.in/web/careers/current-openings",
        "RBI": "https://opportunities.rbi.org.in/",
        "IBPS": "https://www.ibps.in/",
        "NABARD": "https://www.nabard.org/careers.aspx",
        "SIDBI": "https://www.sidbi.in/en/careers",
        "PNB": "https://www.pnbindia.in/Recruitments.aspx",
        "Bank of Baroda": "https://www.bankofbaroda.in/career",
        "Canara Bank": "https://canarabank.com/",
        "Union Bank": "https://www.unionbankofindia.co.in/english/recruitment.aspx",
        "Bank of India": "https://bankofindia.co.in/",
        "Indian Bank": "https://www.indianbank.in/",
        "Central Bank": "https://www.centralbankofindia.co.in/en/recruitments",
        "UCO Bank": "https://www.ucobank.com/",
        "Indian Overseas Bank": "https://www.iob.in/",
        "Bank of Maharashtra": "https://bankofmaharashtra.in/",
        "India Post Payments Bank": "https://www.ippbonline.com/",
        "LIC": "https://licindia.in/",
        "NIACL": "https://www.newindia.co.in/",
        "United India Insurance": "https://uiic.co.in/",
        "National Insurance": "https://nationalinsurance.nic.co.in/",
        "Oriental Insurance": "https://orientalinsurance.org.in/",
        "GIC Re": "https://www.gicre.in/",
        "ECGC": "https://www.ecgc.in/",
        "EXIM Bank": "https://www.eximbankindia.in/",
        "SEBI": "https://www.sebi.gov.in/",
        "IRDAI": "https://irdai.gov.in/",
    },

    # ---------------- DEFENCE & ARMED FORCES ----------------
    "Defence": {
        "Join Indian Army": "https://joinindianarmy.nic.in/",
        "Join Indian Navy": "https://www.joinindiannavy.gov.in/",
        "Indian Air Force": "https://indianairforce.nic.in/",
        "Agniveervayu": "https://agnipathvayu.cdac.in/",
        "Indian Coast Guard": "https://joinindiancoastguard.cdac.in/",
        "Ministry of Defence": "https://www.mod.gov.in/",
        "DRDO RAC": "https://rac.gov.in/",
        "DRDO": "https://www.drdo.gov.in/",
        "HAL": "https://hal-india.co.in/",
        "BEL": "https://bel-india.in/",
        "BEML": "https://www.bemlindia.in/",
        "BDL": "https://bdl-india.in/",
        "Mazagon Dock": "https://mazagondock.in/",
        "GRSE": "https://grse.in/",
        "Cochin Shipyard": "https://cochinshipyard.in/",
        "Goa Shipyard": "https://goashipyard.in/",
        "MIDHANI": "https://midhani-india.in/",
        "Munitions India": "https://munitionsindia.in/",
        "AWEIL": "https://www.aweil.in/",
        "Army Welfare Education Soc.": "https://awesindia.com/",
        "NCC": "https://indiancc.nic.in/",
        "Sainik Schools": "https://sainikschool.ncog.gov.in/",
    },

    # ---------------- POLICE, PARAMILITARY, INTELLIGENCE, SECURITY ----------------
    "Police-Intel": {
        "CRPF": "https://rect.crpf.gov.in/",
        "BSF": "https://rectt.bsf.gov.in/",
        "CISF": "https://www.cisfrecruitment.in/",
        "ITBP": "https://recruitment.itbpolice.nic.in/",
        "SSB": "https://ssb.gov.in/",
        "Assam Rifles": "https://assamrifles.gov.in/",
        "NSG": "https://nsg.gov.in/",
        "NDRF": "https://ndrf.gov.in/",
        "MHA": "https://www.mha.gov.in/",
        "Intelligence Bureau (via MHA)": "https://www.mha.gov.in/en/divisionofmha/intelligence-bureau",
        "NIA": "https://nia.gov.in/",
        "CBI": "https://cbi.gov.in/",
        "NTRO": "https://ntro.gov.in/",
        "NCB": "https://narcoticsindia.nic.in/",
        "Enforcement Directorate": "https://enforcementdirectorate.gov.in/",
        "SFIO": "https://sfio.gov.in/",
        "BPR&D": "https://bprd.nic.in/",
        "Delhi Police": "https://delhipolice.gov.in/",
        "CFSL / Forensic": "https://cfsl.gov.in/",
    },

    # ---------------- CUSTOMS, TAX, REVENUE ----------------
    "Customs-Tax": {
        "CBIC (Customs & GST)": "https://www.cbic.gov.in/",
        "Income Tax": "https://incometaxindia.gov.in/",
        "CBDT": "https://incometaxindia.gov.in/Pages/about-us/central-board-of-direct-taxes.aspx",
        "DRI": "https://dri.nic.in/",
        "CAG": "https://cag.gov.in/",
        "CGA": "https://cga.nic.in/",
    },

    # ---------------- RAILWAYS (all RRBs + PSUs) ----------------
    "Railways": {
        "Indian Railways": "https://indianrailways.gov.in/",
        "RRB Apply (central)": "https://www.rrbapply.gov.in/",
        "RRB Chandigarh": "https://www.rrbcdg.gov.in/",
        "RRB Prayagraj": "https://www.rrbald.gov.in/",
        "RRB Mumbai": "https://www.rrbmumbai.gov.in/",
        "RRB Bhopal": "https://www.rrbbhopal.gov.in/",
        "RRB Bengaluru": "https://www.rrbbnc.gov.in/",
        "RRB Chennai": "https://www.rrbchennai.gov.in/",
        "RRB Kolkata": "https://www.rrbkolkata.gov.in/",
        "RRB Patna": "https://www.rrbpatna.gov.in/",
        "RRB Ahmedabad": "https://www.rrbahmedabad.gov.in/",
        "RRB Ajmer": "https://www.rrbajmer.gov.in/",
        "RRB Gorakhpur": "https://www.rrbgkp.gov.in/",
        "RRB Guwahati": "https://www.rrbguwahati.gov.in/",
        "RRB Jammu": "https://www.rrbjammu.nic.in/",
        "RRB Malda": "https://www.rrbmalda.gov.in/",
        "RRB Ranchi": "https://www.rrbranchi.gov.in/",
        "RRB Secunderabad": "https://www.rrbsecunderabad.gov.in/",
        "RRB Thiruvananthapuram": "https://www.rrbthiruvananthapuram.gov.in/",
        "RRB Bilaspur": "https://www.rrbbilaspur.gov.in/",
        "RRB Siliguri": "https://www.rrbsiliguri.gov.in/",
        "RRB Muzaffarpur": "https://www.rrbmuzaffarpur.gov.in/",
        "RRC (Group D / Apprentice)": "https://www.rrcb.gov.in/",
        "RITES": "https://www.rites.com/",
        "IRCON": "https://ircon.org/",
        "RVNL": "https://rvnl.org/",
        "CONCOR": "https://concorindia.co.in/",
        "IRCTC": "https://irctc.com/",
        "DFCCIL": "https://dfccil.com/",
        "Konkan Railway": "https://konkanrailway.com/",
        "RailTel": "https://www.railtel.in/",
        "CRIS": "https://cris.org.in/",
        "IRFC": "https://irfc.co.in/",
    },

    # ---------------- METRO RAIL ----------------
    "Metro": {
        "Delhi Metro (DMRC)": "https://www.delhimetrorail.com/",
        "Noida Metro": "https://www.nmrcnoida.com/",
        "Lucknow Metro": "https://lmrcl.com/",
        "UP Metro (Kanpur/Agra)": "https://upmetrorail.com/",
        "Mumbai Metro (MMRCL)": "https://mmrcl.com/",
        "MahaMetro (Pune/Nagpur)": "https://www.mahametro.org/",
        "Chennai Metro (CMRL)": "https://chennaimetrorail.org/",
        "Bengaluru Metro (BMRCL)": "https://english.bmrc.co.in/",
        "Kolkata Metro": "https://mtp.indianrailways.gov.in/",
        "Hyderabad Metro": "https://www.ltmetro.com/",
        "Kochi Metro": "https://kmrl.co.in/",
        "Jaipur Metro": "https://transport.rajasthan.gov.in/jmrc",
        "Ahmedabad/Gujarat Metro": "https://gujaratmetrorail.com/",
        "Bhopal/Indore Metro": "https://mpmetrorail.com/",
        "Patna Metro": "https://pmrcl.org/",
        "NCRTC (RRTS)": "https://ncrtc.in/",
        "NHSRCL (Bullet Train)": "https://nhsrcl.in/",
    },

    # ---------------- TEACHING & EDUCATION ----------------
    "Teaching": {
        "KVS": "https://kvsangathan.nic.in/",
        "NVS": "https://navodaya.gov.in/",
        "CTET": "https://ctet.nic.in/",
        "NESTS (EMRS)": "https://nests.tribal.gov.in/",
        "UGC": "https://www.ugc.gov.in/",
        "NCERT": "https://ncert.nic.in/",
        "IGNOU": "https://www.ignou.ac.in/",
        "DSSSB (Delhi)": "https://dsssb.delhi.gov.in/",
        "Dept of School Education": "https://dsel.education.gov.in/",
        "IIT Recruitment (JoSAA/Indiv.)": "https://www.iitd.ac.in/",
        "NIT Recruitment (NITs)": "https://www.nitt.edu/",
    },

    # ---------------- PSUs: ENERGY, POWER, OIL & GAS, MINING, STEEL ----------------
    "PSU-Tech": {
        "ISRO": "https://www.isro.gov.in/Careers.html",
        "BARC": "https://www.barc.gov.in/",
        "NPCIL": "https://npcilcareers.co.in/",
        "DAE": "https://dae.gov.in/",
        "BHEL": "https://www.bhel.com/",
        "ECIL": "https://www.ecil.co.in/",
        "Central Electronics Ltd": "https://celindia.co.in/",
        "NTPC": "https://careers.ntpc.co.in/",
        "Power Grid": "https://www.powergrid.in/",
        "NHPC": "https://www.nhpcindia.com/",
        "SJVN": "https://sjvn.nic.in/",
        "NLC India": "https://www.nlcindia.in/",
        "Coal India": "https://www.coalindia.in/",
        "SAIL": "https://www.sail.co.in/",
        "NMDC": "https://www.nmdc.co.in/",
        "NALCO": "https://nalcoindia.com/",
        "MECON": "https://meconlimited.co.in/",
        "ONGC": "https://ongcindia.com/",
        "IOCL": "https://iocl.com/",
        "BPCL": "https://www.bharatpetroleum.in/",
        "HPCL": "https://www.hindustanpetroleum.com/",
        "GAIL": "https://gailonline.com/",
        "Oil India": "https://www.oil-india.com/",
        "EIL": "https://engineersindia.com/",
        "AAI (Airports)": "https://www.aai.aero/",
        "NHAI": "https://nhai.gov.in/",
        "CPWD": "https://cpwd.gov.in/",
        "BSNL": "https://www.bsnl.co.in/",
        "C-DOT": "https://www.cdot.in/",
        "C-DAC": "https://www.cdac.in/",
        "STPI": "https://stpi.in/",
        "BIS": "https://www.bis.gov.in/",
        "TRAI": "https://www.trai.gov.in/",
        "Port Trusts / Shipping": "https://shipmin.gov.in/",
        "FCI": "https://fci.gov.in/",
        "India Post": "https://www.indiapost.gov.in/",
        "Indian Oil Pipelines": "https://iocl.com/",
    },

    # ---------------- HEALTH & MEDICAL ----------------
    "Health": {
        "AIIMS (central)": "https://www.aiimsexams.ac.in/",
        "ESIC": "https://www.esic.gov.in/",
        "PGIMER": "https://pgimer.edu.in/",
        "NHM": "https://nhm.gov.in/",
        "CGHS": "https://cghs.gov.in/",
    },

    # ---------------- JUDICIARY ----------------
    "Judiciary": {
        "Supreme Court": "https://www.sci.gov.in/recruitments/",
        "Delhi High Court": "https://delhihighcourt.nic.in/",
        "Allahabad High Court": "https://www.allahabadhighcourt.in/",
        "Uttarakhand High Court": "https://highcourtofuttarakhand.gov.in/",
    },

    # ---------------- STATE PSCs / SSBs / POLICE BOARDS ----------------
    "States": {
        "UKPSC (Uttarakhand)": "https://psc.uk.gov.in/",
        "UKSSSC (Uttarakhand)": "https://sssc.uk.gov.in/",
        "Uttarakhand Police": "https://uttarakhandpolice.uk.gov.in/",
        "UPPSC (UP)": "https://uppsc.up.nic.in/",
        "UPSSSC (UP)": "https://upsssc.gov.in/",
        "UP Police Board": "https://uppbpb.gov.in/",
        "BPSC (Bihar)": "https://bpsc.bihar.gov.in/",
        "BSSC (Bihar)": "https://bssc.bihar.gov.in/",
        "RPSC (Rajasthan)": "https://rpsc.rajasthan.gov.in/",
        "RSMSSB (Rajasthan)": "https://rsmssb.rajasthan.gov.in/",
        "MPPSC (MP)": "https://mppsc.mp.gov.in/",
        "MPESB (MP)": "https://esb.mp.gov.in/",
        "HPSC (Haryana)": "https://hpsc.gov.in/",
        "HSSC (Haryana)": "https://hssc.gov.in/",
        "PPSC (Punjab)": "https://ppsc.gov.in/",
        "PSSSB (Punjab)": "https://sssb.punjab.gov.in/",
        "HPPSC (Himachal)": "https://hppsc.hp.gov.in/",
        "HPRCA (Himachal)": "https://hpsssb.hp.gov.in/",
        "JKPSC (J&K)": "https://jkpsc.nic.in/",
        "JKSSB (J&K)": "https://jkssb.nic.in/",
        "GPSC (Gujarat)": "https://gpsc.gujarat.gov.in/",
        "GSSSB (Gujarat)": "https://gsssb.gujarat.gov.in/",
        "MPSC (Maharashtra)": "https://mpsc.gov.in/",
        "TNPSC (Tamil Nadu)": "https://tnpsc.gov.in/",
        "KPSC (Karnataka)": "https://kpsc.kar.nic.in/",
        "Kerala PSC": "https://keralapsc.gov.in/",
        "APPSC (Andhra)": "https://psc.ap.gov.in/",
        "TGPSC (Telangana)": "https://tgpsc.gov.in/",
        "OPSC (Odisha)": "https://opsc.gov.in/",
        "WBPSC (West Bengal)": "https://wbpsc.gov.in/",
        "WBSSC (West Bengal)": "https://wbssc.gov.in/",
        "JPSC (Jharkhand)": "https://jpsc.gov.in/",
        "JSSC (Jharkhand)": "https://jssc.nic.in/",
        "CGPSC (Chhattisgarh)": "https://psc.cg.gov.in/",
        "CG Vyapam": "https://vyapam.cgstate.gov.in/",
        "APSC (Assam)": "https://apsc.nic.in/",
        "SLPRB Assam": "https://slprbassam.in/",
        "Delhi Govt Jobs": "https://delhi.gov.in/",
        "Goa PSC": "https://gpsc.goa.gov.in/",
        "Tripura PSC": "https://tpsc.tripura.gov.in/",
        "Manipur PSC": "https://mpscmanipur.gov.in/",
        "Meghalaya PSC": "https://mpsc.nic.in/",
        "Mizoram PSC": "https://mpsc.mizoram.gov.in/",
        "Nagaland PSC": "https://npsc.nagaland.gov.in/",
        "Arunachal PSC": "https://apsc.nic.in/",
        "Sikkim PSC": "https://spscskm.gov.in/",
    },

    # ---------------- AGGREGATORS (safety net: they cover everything above) ----------------
    "Aggregators": {
        "FreeJobAlert": "https://www.freejobalert.com/",
        "SarkariResult": "https://www.sarkariresult.com/latestjob/",
        "SarkariExam": "https://www.sarkariexam.com/",
        "RojgarResult": "https://www.rojgarresult.com/",
        "Sarkari Naukri (FJA all-India)": "https://www.freejobalert.com/government-jobs/",
        "Naukri Govt": "https://www.naukri.com/government-jobs",
    },
}


# ======================= ADDED: MORE SECTORS (v3) =======================
SOURCES.update({

    # ---------------- FOREST, ENVIRONMENT, WILDLIFE ----------------
    "Forest-Env": {
        "MoEFCC": "https://moef.gov.in/",
        "ICFRE": "https://icfre.gov.in/",
        "Wildlife Institute of India": "https://wii.gov.in/",
        "Forest Survey of India": "https://fsi.nic.in/",
        "IGNFA": "https://ignfa.gov.in/",
        "CPCB": "https://cpcb.nic.in/",
        "NTCA (Tiger Authority)": "https://ntca.gov.in/",
        "Uttarakhand Forest Dept": "https://forest.uk.gov.in/",
        "UP Forest Dept": "https://forest.up.nic.in/",
        "MP Forest Dept": "https://mpforest.gov.in/",
        "Rajasthan Forest Dept": "https://forest.rajasthan.gov.in/",
        "Himachal Forest Dept": "https://hpforest.nic.in/",
        "Haryana Forest Dept": "https://haryanaforest.gov.in/",
        "Odisha Forest Dept": "https://forest.odisha.gov.in/",
        "Karnataka Forest Dept": "https://aranya.gov.in/",
        "Maharashtra Forest Dept": "https://mahaforest.gov.in/",
        "Kerala Forest Dept": "https://forest.kerala.gov.in/",
    },

    # ---------------- AGRICULTURE, FOOD, FERTILISER, FISHERIES ----------------
    "Agri-Food": {
        "FCI": "https://fci.gov.in/",
        "FSSAI": "https://fssai.gov.in/",
        "NAFED": "https://nafed-india.com/",
        "Central Warehousing Corp": "https://cewacor.nic.in/",
        "State Warehousing (various)": "https://cewacor.nic.in/",
        "NFL (Fertilizers)": "https://www.nationalfertilizers.com/",
        "RCF": "https://www.rcfltd.com/",
        "IFFCO": "https://www.iffco.in/",
        "KRIBHCO": "https://www.kribhco.net/",
        "Coffee/Tea/Spices/Rubber Boards": "https://www.indiacoffee.org/",
        "NABARD (Agri Dev)": "https://www.nabard.org/careers.aspx",
        "ICAR Institutes": "https://icar.org.in/",
        "Dept of Fisheries": "https://dof.gov.in/",
        "MPEDA": "https://mpeda.gov.in/",
        "APEDA": "https://apeda.gov.in/",
        "NDDB": "https://www.nddb.coop/",
        "Cotton Corp (CCI)": "https://cotcorp.org.in/",
        "Jute Corp": "https://jutecorp.in/",
    },

    # ---------------- SCIENCE, SURVEY, WEATHER, STATISTICS, SPACE ----------------
    "Science-Survey": {
        "IMD (Weather)": "https://mausam.imd.gov.in/",
        "Survey of India": "https://surveyofindia.gov.in/",
        "Geological Survey (GSI)": "https://www.gsi.gov.in/",
        "NSO / MoSPI": "https://mospi.gov.in/",
        "Census India": "https://censusindia.gov.in/",
        "NIC / MeitY": "https://www.meity.gov.in/",
        "ISRO": "https://www.isro.gov.in/Careers.html",
        "NRSC": "https://www.nrsc.gov.in/",
        "PRL": "https://www.prl.res.in/",
        "TIFR": "https://www.tifr.res.in/",
        "IISc": "https://iisc.ac.in/",
        "IISER (various)": "https://www.iiserpune.ac.in/",
        "NPL": "https://www.nplindia.org/",
        "CDRI / CSIR labs": "https://www.csir.res.in/",
        "NIELIT": "https://www.nielit.gov.in/",
        "NIT/IIT Non-Teaching": "https://www.iitk.ac.in/",
        "National Archives": "https://nationalarchives.nic.in/",
    },

    # ---------------- SECRETARIATS, CONSTITUTIONAL BODIES, MINISTRIES ----------------
    "Ministries-Bodies": {
        "Lok Sabha Secretariat": "https://sansad.in/ls",
        "Rajya Sabha Secretariat": "https://sansad.in/rs",
        "Election Commission": "https://eci.gov.in/",
        "Staff Selection Commission (CPO etc.)": "https://ssc.gov.in/",
        "NITI Aayog": "https://niti.gov.in/",
        "EPFO": "https://www.epfindia.gov.in/",
        "NPS Trust / PFRDA": "https://www.pfrda.org.in/",
        "UIDAI": "https://uidai.gov.in/",
        "NIC / National e-Gov": "https://www.nic.in/",
        "Press Information (PIB) Jobs": "https://pib.gov.in/",
        "Dept of Posts": "https://www.indiapost.gov.in/",
        "Ministry of Labour": "https://labour.gov.in/",
        "Ministry of Finance": "https://finmin.nic.in/",
        "Ministry of External Affairs": "https://mea.gov.in/",
        "Ministry of Education": "https://www.education.gov.in/",
        "Ministry of Health": "https://mohfw.gov.in/",
        "Ministry of Textiles": "https://texmin.nic.in/",
        "Ministry of Tribal Affairs": "https://tribal.nic.in/",
        "Sports Authority of India": "https://sportsauthorityofindia.nic.in/",
        "Security Printing & Minting (SPMCIL)": "https://spmcil.com/",
        "Rail Coach / Loco Works": "https://indianrailways.gov.in/",
        "Cooperative Societies": "https://cooperation.gov.in/",
    },

    # ---------------- STATE POWER, TRANSPORT, LOCAL BODIES, REVENUE ----------------
    "State-Utilities": {
        "UPPCL (UP Power)": "https://uppcl.org/",
        "UPCL (Uttarakhand Power)": "https://www.upcl.org/",
        "PTCUL": "https://ptcul.org/",
        "UJVNL": "https://uttarakhandjalvidyut.com/",
        "RVPN (Rajasthan Power)": "https://energy.rajasthan.gov.in/",
        "MSEDCL (Maharashtra)": "https://www.mahadiscom.in/",
        "TANGEDCO / TNPDCL": "https://www.tnebltd.gov.in/",
        "KSEB (Kerala)": "https://kseb.in/",
        "BESCOM (Karnataka)": "https://bescom.karnataka.gov.in/",
        "DHBVN / UHBVN (Haryana)": "https://uhbvn.org.in/",
        "UPSRTC (UP Roadways)": "https://upsrtc.com/",
        "UKSRTC / Uttarakhand Transport": "https://utc.uk.gov.in/",
        "Delhi Jal Board": "https://delhijalboard.delhi.gov.in/",
        "MCD (Delhi)": "https://mcdonline.nic.in/",
        "BMC (Mumbai)": "https://portal.mcgm.gov.in/",
        "GHMC (Hyderabad)": "https://www.ghmc.gov.in/",
        "Revenue / Patwari (via state PSC/SSB)": "https://upsssc.gov.in/",
        "Anganwadi (state WCD portals)": "https://wcd.nic.in/",
        "Gramin Dak Sevak (GDS)": "https://indiapostgdsonline.gov.in/",
    },

    # ---------------- MORE PSUs (MANUFACTURING, AVIATION, SHIPPING, PHARMA, TELECOM) ----------------
    "PSU-More": {
        "Air India / AI Airport Services": "https://www.airindia.com/",
        "AIATSL": "https://aiatsl.com/",
        "Pawan Hans": "https://www.pawanhans.co.in/",
        "Hindustan Aeronautics (careers)": "https://hal-india.co.in/Careers",
        "NBCC": "https://www.nbccindia.in/",
        "HUDCO": "https://hudco.org/",
        "NHB": "https://nhb.org.in/",
        "REC Ltd": "https://recindia.nic.in/",
        "PFC": "https://www.pfcindia.com/",
        "IREDA": "https://www.ireda.in/",
        "NBPC / Heavy Engineering (HEC)": "https://hecltd.com/",
        "Hindustan Copper": "https://hindustancopper.com/",
        "Hindustan Zinc / Vedanta (private ref)": "https://www.hzlindia.com/",
        "IRCON / Water (WAPCOS)": "https://wapcos.co.in/",
        "Hindustan Antibiotics / HLL": "https://lifecarehll.com/",
        "BCPL / KIOCL": "https://kioclltd.in/",
        "MTNL": "https://mtnl.in/",
        "ITI Ltd": "https://itiltd.in/",
        "Tata Memorial (central)": "https://tmc.gov.in/",
        "Shipping Corp (SCI)": "https://shipindia.com/",
        "Kandla/Deendayal Port": "https://www.deendayalport.gov.in/",
        "Mumbai/JNPA/Paradip Ports": "https://jnport.gov.in/",
        "Cochin Port": "https://cochinport.gov.in/",
    },
})
